language: ruby
rvm:
- 2.1.6
bundler_args: "--without development --jobs 4"
script:
- bundle exec rake rubocop
- bundle exec rake
deploy:
  provider: heroku
  api_key:
    secure: eGuCxDpOQRZi7o3CwrLazbAxK545Hhg00vH8jhxTK+VZaF5q2DNw5ZPXX5wVV9Namm5hJePp5nMZtk767o3MXuAwGqKgIR+EMvZ9CxIgylSmBXA04kKcYWFm5eTWFa6Os3XyY2UaulcFhvMu/cROHJc/xnR/e8cZjY7LIxld98k=
  app: docker-private-registry
  on:
    repo: Aigeruth/docker-private-registry
    branch: master
  strategy: api
