# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'chef/ubuntu-14.04'
  config.vm.box_check_update = true
  config.omnibus.chef_version = '11.12.8'

  config.vm.synced_folder '../../', '/docker-registry'

  config.vm.provision 'chef_solo' do |chef|
    chef.add_recipe 'docker'
    chef.add_recipe 'ruby_build'
    chef.add_recipe 'rbenv::system'
    chef.add_recipe 'rbenv::vagrant'

    chef.json = {
      rbenv: {
        rubies: ['2.1.3'],
        global: '2.1.3',
        gems: {
          '2.1.3' => [{ 'name' => 'bundler' }]
        }
      },
      docker: {
        group_members: ['vagrant'],
        version: '1.3.0'
      }
    }
  end

  config.vm.provision 'shell', path: 'test_docker-registry.sh', run: 'always'
end
